{% set name = "QRules" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 372db0b5805234b58759ad6052ea327464cb8852ed744a23d10308ebc5607899

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=61.2
    - setuptools-scm
  run:
    - python >=3.7
    - attrs >=20.1.0
    - jsonschema
    - particle
    - python-constraint2
    - PyYAML
    - tqdm >=4.24.0
    - typing-extensions

test:
  imports:
    - qrules
    - qrules.io
    - qrules.conservation_rules
    - qrules.particle
    - qrules.quantum_numbers
    - qrules.topology
    - qrules.transition

about:
  home: https://github.com/ComPWA/qrules
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Rule based particle reaction problem solver on a quantum number level

  description: |
    QRules is a Python package for **validating and generating particle reactions**
    using quantum number conservation rules. The user only has to provide a certain
    set of boundary conditions (initial and final state, allowed interaction types,
    expected decay topologies, etc.). QRules will then span the space of allowed
    quantum numbers over all allowed decay topologies and particle instances that
    correspond with the sets of allowed quantum numbers it has found.

    The resulting state transition objects are particularly useful for **amplitude
    analysis / Partial Wave Analysis** as they contain all information (such as
    expected masses, widths, and spin projections) that is needed to formulate an
    amplitude model.

  dev_url: https://github.com/ComPWA/qrules
  doc_url: https://qrules.readthedocs.io

extra:
  recipe-maintainers:
    - redeboer
